### PR TITLE
Migrate block mode crates

### LINKED ISSUE #5: Intermediate IV exposing for save/restore APIs
Hello folks, would you accept a PR similar to [block-ciphers/pull/227](https://github.com/RustCrypto/block-ciphers/pull/227) as suggested by @newpavlov, allowing to serialize ciphers and continue operation later? Note that even without the exposure, the cryptor can recover the internal IV state at any moment, but this would require additional caching (one full ciphertext block for CFB, and one ciphertext block + one plaintext block + one xor for OFB). Perhaps we could implement the same `IvState` trait.

Regards

cc. @jethrogb

### LINKED ISSUE #6: block-modes: add opaque Debug implementations
Depends on RustCrypto/utils#79

### PR DESCRIPTION
**Pull request by newpavlov**
Depends on RustCrypto/utils#566, RustCrypto/traits#727, and RustCrypto/block-ciphers#284.

Closes #5
Closes #6

TODO:
- [x] Add test vectors for IGE and PCBC
- [x] Impl `IvState` for CFB
- [x] Impl zeroizing `Drop` for CTR
- [x] Add examples to crate docs

### CODE REVIEW

**Comment by M1cha** [comment]
why didn't this include `ecb`? It was deleted from `block-ciphers` but not imported into this crate.

**Comment by M1cha** [comment]
Thanks, but I currently use `block_modes::Ecb<aes::Aes128, block_modes::block_padding::NoPadding>` and I don't see any padding options in `aes` 0.8

**Comment by newpavlov** [comment]
With the new versions you now specify padding on [encryption](https://docs.rs/cipher/0.4.0/cipher/trait.BlockEncrypt.html#method.encrypt_padded)/[decryption](https://docs.rs/cipher/0.4.0/cipher/trait.BlockDecrypt.html#method.decrypt_padded) methods, not on a block mode type. For example, see [`cbc` docs](https://docs.rs/cbc). For ECB instead of `cbc::Encryptor<aes::Aes128>` you would simply use `aes::Aes128`.

**Comment by liyongjing** [comment]
where is  Ecb<Aes128, Pkcs7>

**Comment by newpavlov** [comment]
ECB is "implemented" by block ciphers directly, i.e. you can use methods like [`encrypt_padded`](https://docs.rs/cipher/latest/cipher/trait.BlockEncrypt.html#method.encrypt_padded) on `Aes128`.

**Comment by liyongjing** [comment]
aes = "0.7.0"
block-modes = "0.8.1"
 AES/ECB/PKCS5Padding impl  on old-version
```
    use aes::Aes128;
    use block_modes::block_padding::Pkcs7;
    use block_modes::{BlockMode, Ecb};

    type Aes128Ecb = Ecb<Aes128, Pkcs7>;
    let cipher = Aes128Ecb::new_from_slices(&key, &key).unwrap();
    let mut buffer = [0u8; 32];
    let pos = plaintext.len();
    buffer[..pos].copy_from_slice(plaintext);
    let ciphertext = cipher.encrypt(&mut buffer, pos).unwrap();
```

**Comment by newpavlov** [comment]
Use the linked methods directly on `Aes128` (ee docs for [`BlockEncrypt`](https://docs.rs/cipher/latest/cipher/trait.BlockEncrypt.html) and [`BlockDecrypt`](https://docs.rs/cipher/latest/cipher/trait.BlockDecrypt.html)). You do not need `Ecb` with the new crate versions. Padding is passed as a type argument to the padding-based methods.

**Pull request merged**
