### PR TITLE
Implement belt-ctr

### LINKED ISSUE #35: belt-ctr implementation
Hello!
Just tried to implement STB 34.101.31-2020 belt-ctr cipher:
image

With code:
```rust
pub type BeltCtr = ctr::Ctr128LE<belt_block::BeltBlock>;

#[cfg(test)]
mod tests {
    use ctr::cipher::{KeyIvInit, StreamCipher};
    use hex_literal::hex;
    use super::*;

    #[test]
    fn test() {
        let x = hex!("B194BAC8 0A08F53B 366D008E 584A5DE4 8504FA9D 1BB6C7AC 252E72C2 02FDCE0D 5BE3D612 17B96181 FE6786AD 716B890B");
        let k = hex!("E9DEE72C 8F0C0FA6 2DDB49F4 6F739647 06075316 ED247A37 39CBA383 03A98BF6");
        let s = hex!("BE329713 43FC9A48 A02A885F 194B09A1");
        let y = hex!("52C9AF96 FF50F644 35FC43DE F56BD797 D5B5B1FF 79FB4125 7AB9CDF6 E63E81F8 F0034147 3EAE4098 33622DE0 5213773A");

        let mut cipher = BeltCtr::new(&k.into(), &s.into());
        let mut buf = x.to_vec();
        cipher.apply_keystream(&mut buf);
        assert_eq!(buf, y);
    }
}
```

And got some problems:
gen_ks_block return bytes:
```
72 8a f3 c2   9a e7 56 4f 
54 01 c9 10   13 31 d8 a4
```

But in STB, we need to add +1 in LE (so, bytes will be):
```
73 8a f3 c2   9a e7 56 4f  
54 01 c9 10   13 31 d8 a3
```

And it should be reversed. What I suppose to do, to resolve this problem? Implement self own gen_ks_block?
Thank you!
@newpavlov

### PR DESCRIPTION
**Pull request by makavity**
Hello! Just implemented belt-ctr.
Have questions about :)
1. Am I need to implement BE Flavor?
2. Should I implement seek and pos methods?

Thanks!

Closes #35

### CODE REVIEW

**Comment by makavity** [comment]
Hm, okay. So, should I also use cipher as generic?

**Comment by newpavlov** [comment]
Yes, it would be preferable. But you can make `BeltBlock` the default cipher. It can looks something like this:
```rust
struct BeltCtr<C = BeltBlock>
where C: BlockEncrypt + BlockSizeUser<BlockSize = U16>
{ ... }
```

**Comment by makavity** [comment]
I don't know, should I completely remove nonce and use CtrNonce128 as struct type?
Also, which way would be better to implement seek, if I use ctr like s variable from standard?

**Comment by newpavlov** [comment]
No, you should not implement `StreamCipher` directly. It's a byte level interface, which requires buffering of keystream blocks. Your current implementation will lose keystream bytes when fed messages with length not multiple of the block size.

You should implement `StreamCipherCore` and `StreamSeekCore` for `BeltCtrCore`. Then you can introduce `pub type CtrBlock<C> =  StreamCipherCoreWrapper<CtrBlockCore<c>>;`. The wrapper will handle buffering and implementation of `StreamCipher` and `StreamCipherSeek` for the resulting type.

**Comment by newpavlov** [comment]
I have implemented the required traits. Our trait hierarchy is... a bit non-trivial, so it can be hard to write a proper implementation if you are not familiar with it. Take a look if you are interested and feel free to ask any questions about it.

**Comment by makavity** [comment]
That looks awesome, thank you for great example! I have a question about tests, how to get blob format for tests?

**Comment by newpavlov** [comment]
It's done using this [utility](https://github.com/RustCrypto/utils/blob/master/blobby/examples/convert.rs) in the `blobby` crate. For encoding you feed it a text file containing hex strings. Each line is an entry, stream ciphers require 4 entries per test vector (key, IV, plaintext, ciphertext).

**Comment by makavity** [comment]
Can you also tell me about remaining blocks and why it is implemented like this?

**Comment by newpavlov** [comment]
After generating `u128::MAX` blocks the keystream wraps around, which should not happen. Of course, it's impossible to generate so much data in practice, but with the seeking capability user may erroneously set keystream position near the end. So we calculate how much blocks were "generated" (the `used` variable), and then subtract it from the total number of blocks. This value is then used in the wrapper to return an error on potential keystream wrapping.

**Pull request merged**
