### PR TITLE
Belt-Ecb

### PR DESCRIPTION
**Pull request by makavity**
Hello!
Implemented belt-ecb. 
I know it is not the last version, but I have no idea how to use traits with CTS modes.
So, now, I have questions:
1. Can I use not Buf version of Encryptor/Decryptor?
2. Benches is wrong, I suggest.

Any ideas, how to implement it more correctly?
Thanks.
@newpavlov

### CODE REVIEW

**Comment by newpavlov** [comment]
I have draft implementation of generic CTS2 and CTS3 modes (CTS1 is a bit more difficult, since it can be applied only to CBC), which should cover belt-ecb and belt-cbc. I will try to make PR with it later this week.

**Comment by makavity** [comment]
@newpavlov Hello!
Any updates? :)

**Comment by makavity** [comment]
@newpavlov hey. Can you share your draft? Maybe i can finalize it.

**Comment by newpavlov** [comment]
Ah, sorry for the delay. I had some bugs in my implementation, I intended to publish the crate after fixing them, but forgot about it... I will try to do it during this weekend, if not, I'll publish buggy draft.

**Comment by makavity** [comment]
@newpavlov hello! Any updates? :)

**Comment by makavity** [comment]
@newpavlov hey. Could you upload draft please?

**Comment by makavity** [comment]
@newpavlov hey, need it for BPACE implementation. Any updates?

**Comment by makavity** [comment]
@newpavlov hey. Any updates about CS2?

**Comment by makavity** [comment]
@newpavlov hey. Any updates about CTS?

**Comment by makavity** [comment]
@newpavlov hello, any updates for CTS?

**Comment by newpavlov** [comment]
Sorry for the late response!

Closing in favor of #70 (see `EcbCs2Enc` and `EcbCs2Dec`).

**Comment by makavity** [comment]
Thank you so much!

**Pull request closed without merging**
